### ISSUE TITLE
能不能支持某些行按照行合并，某些按照列合并，行或者列合并可以同时指定？

### ISSUE THREAD

**Issue by sisihuisi** [yuexiaoliang/table-merge#1]
能不能支持某些行按照行合并，某些按照列合并，行或者列合并可以同时指定？

**Comment by yuexiaoliang** [comment]
@sisihuisi 之前倒是考虑过这两个功能的，但是后来发现现有的常用 UI 框架好像大多都不支持这样，这样就相当于 table-merge 虽然实现了，但是却和没实现一样，除非自己写个 table 出来。
