### ISSUE TITLE
列中有多余的字段, 合并就会失败

### ISSUE THREAD

**Issue by a15218378694** [yuexiaoliang/table-merge#3]
指定key可以解决, 但放到项目中报错了, 估计是一些容错没做好, 麻烦看下吧
![image](https://user-images.githubusercontent.com/29919045/221342117-366513e2-4304-40dc-9115-d2f35c2aaaae.png)

![image](https://user-images.githubusercontent.com/29919045/221342102-13c6a03e-774d-428b-ab23-e6f636b14123.png)

**Comment by a15218378694** [comment]
目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的

**Comment by yuexiaoliang** [comment]
嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。

**Comment by yuexiaoliang** [comment]
> 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的

嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694

**Comment by yuexiaoliang** [comment]
> 指定key可以解决, 但放到项目中报错了, 估计是一些容错没做好, 麻烦看下吧 ![image](https://user-images.githubusercontent.com/29919045/221342117-366513e2-4304-40dc-9115-d2f35c2aaaae.png)
> 
> ![image](https://user-images.githubusercontent.com/29919045/221342102-13c6a03e-774d-428b-ab23-e6f636b14123.png)

我这里试了试没问题呀

![合并](https://user-images.githubusercontent.com/37929159/221343968-cbd35118-3566-4d9c-8998-c0b9a5a6869f.png)

``` vue
<script setup lang="ts">
import tableMergeElementPlus from '@table-merge/element-plus';

const data = [
  { id: 23, l1: '信息流', l2: '横版视频流', l3: '横版视频流' },
  { id: 22, l1: '信息流', l2: '横版视频流', l3: '横版视频流2' },
  { id: 21, l1: '信息流', l2: '横版视频流2', l3: '横版视频流' },
  { id: 20, l1: '信息流', l2: '横版视频流', l3: '横版视频流' },
  { id: 19, l1: '信息流', l2: '横版视频流', l3: '横版视频流' },
];

const columns = [
  // { prop: 'id', label: 'ID', align: 'center' },
  { prop: 'l1', label: 'A列', align: 'center' },
  { prop: 'l2', label: 'B列', align: 'center' },
  { prop: 'l3', label: 'C列', align: 'center' },
];
</script>

<template>
  <el-table :data="data" :span-method="tableMergeElementPlus(data, {keys: ['l1','l2','l3']})" border>
    <el-table-column v-for="col in columns" :key="col.prop" v-bind="col" />
  </el-table>
</template>
```

``` vue
<script setup lang="ts">
import tableMergeElementPlus from '@table-merge/element-plus';

const data = [
  { id: 23, l1: '信息流', l2: '横版视频流', l3: '横版视频流' },
  { id: 22, l1: '信息流', l2: '横版视频流', l3: '横版视频流2' },
  { id: 21, l1: '信息流', l2: '横版视频流2', l3: '横版视频流' },
  { id: 20, l1: '信息流', l2: '横版视频流', l3: '横版视频流' },
  { id: 19, l1: '信息流', l2: '横版视频流', l3: '横版视频流' }
];
</script>

<template>
  <el-table :data="data" :span-method="tableMergeElementPlus(data, { keys: ['l1', 'l2', 'l3'] })" border>
    <!-- <el-table-column prop="id" label="ID"></el-table-column> -->
    <el-table-column prop="l1" label="L1"></el-table-column>
    <el-table-column prop="l2" label="L2"></el-table-column>
    <el-table-column prop="l3" label="L3"></el-table-column>
  </el-table>
</template>
```

**Comment by a15218378694** [comment]
自定义渲染的列，不需要定义prop，因为有row



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3)




  
目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的
  
嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694

**Comment by yuexiaoliang** [comment]
> 自定义渲染的列，不需要定义prop，因为有row
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月25日(周六) 下午3:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我明白你说的场景了，现在确实不支持

**Comment by a15218378694** [comment]
mock一些prop放上去，可以吧，就是keys和column中都写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3)




  
自定义渲染的列，不需要定义prop，因为有row
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
我明白你说的场景了，现在确实不支持

**Comment by yuexiaoliang** [comment]
> mock一些prop放上去，可以吧，就是keys和column中都写
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月25日(周六) 下午3:24 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 自定义渲染的列，不需要定义prop，因为有row … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; 我明白你说的场景了，现在确实不支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

只要 prop 和 data 中的数据能对起来就行

**Comment by a15218378694** [comment]
对应起来的话，会不会乱合并哦，有些列是不需要合并行的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月25日(周六) 下午3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3)




  
mock一些prop放上去，可以吧，就是keys和column中都写
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:24 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 自定义渲染的列，不需要定义prop，因为有row … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; 我明白你说的场景了，现在确实不支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
  
只要 prop 和 data 中的数据能对起来就行

**Comment by yuexiaoliang** [comment]
> 对应起来的话，会不会乱合并哦，有些列是不需要合并行的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月25日(周六) 下午3:31 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) mock一些prop放上去，可以吧，就是keys和column中都写 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:24 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 自定义渲染的列，不需要定义prop，因为有row … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; 我明白你说的场景了，现在确实不支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; 只要 prop 和 data 中的数据能对起来就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

如果没限制的话有可能会出现你说的情况，现在可以用的配置有 `range` 和 `spanType` ，不知道是否能满足。

**Comment by a15218378694** [comment]
> 

真的会乱合并, 我现在试试你说的range 和 spanType

**Comment by a15218378694** [comment]
> > 对应起来的话，会不会乱合并哦，有些列是不需要合并行的
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年2月25日(周六) 下午3:31 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) mock一些prop放上去，可以吧，就是keys和column中都写 … ---原始邮件--- 发件人: @.> 发送时间: 2023年2月25日(周六) 下午3:24 收件人: @.>; 抄送: @.@.>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 自定义渲染的列，不需要定义prop，因为有row … ---原始邮件--- 发件人: @.> 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.>; 抄送: @.@.>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 我明白你说的场景了，现在确实不支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 只要 prop 和 data 中的数据能对起来就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 如果没限制的话有可能会出现你说的情况，现在可以用的配置有 `range` 和 `spanType` ，不知道是否能满足。

配合range 和 spanType还是没解决问题

**Comment by a15218378694** [comment]
range: { col: [0,4] }这好像才是从第一列开始

**Comment by yuexiaoliang** [comment]
> > > 对应起来的话，会不会乱合并哦，有些列是不需要合并行的
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年2月25日(周六) 下午3:31 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) mock一些prop放上去，可以吧，就是keys和column中都写 … ---原始邮件--- 发件人: @.> 发送时间: 2023年2月25日(周六) 下午3:24 收件人: @.>; 抄送: @.@.>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 自定义渲染的列，不需要定义prop，因为有row … ---原始邮件--- 发件人: @.> 发送时间: 2023年2月25日(周六) 下午3:06 收件人: @.>; 抄送: @.@.>; 主题: Re: [yuexiaoliang/table-merge] 列中有多余的字段, 合并就会失败 (Issue #3) 目前的问题是，每一列都必须有prop, 这就坑了，有些是自定义渲染的 嗯，但是 element 本身也是需要 prop 的啊，没有 prop 怎么渲染列数据呀。 @a15218378694 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 我明白你说的场景了，现在确实不支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 只要 prop 和 data 中的数据能对起来就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> > 
> > 
> > 如果没限制的话有可能会出现你说的情况，现在可以用的配置有 `range` 和 `spanType` ，不知道是否能满足。
> 
> 配合range 和 spanType还是没解决问题

咳咳，还不够强大，功能不够丰富！

**Comment by a15218378694** [comment]
可否发下微，我加你，麻烦了

**Comment by yuexiaoliang** [comment]
> 可否发下微，我加你，麻烦了

yuexiaoliang1993
